# Process Automation using Python


 - This program will:
 - Access Google Drive > Download a file > Extract information > Send by e-mail
 - Dataset: https://www.kaggle.com/gregorut/videogamesales

In [102]:
import pyautogui as pg
import pyperclip as pc
import time
import pandas as pd

#It needs a pause between a command and the next one (in seconds)
pg.PAUSE = 1

#Open a new tab
pg.hotkey("ctrl","t")

#Copy and paste the link 
pc.copy("https://docs.google.com/spreadsheets/d/1sQ7S8Cb06WQkJZNQBj28JIy1Jgjem1Au/edit?usp=sharing&ouid=104384067204412215105&rtpof=true&sd=true")
pg.hotkey("ctrl","v")
pg.press("enter")

#Time to load  the information(in seconds)
time.sleep(10)

#Download the data
pg.click(x=64, y=104)
pg.moveTo(x=156, y=315)

pg.move(200, 0)
pg.click(clicks=2)

In [104]:
#Change to your directory
df = pd.read_excel(r"C:\Users\Fernanda\Downloads\vgsales.xlsx", index_col=0)

display(df)

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Rank,,,,,,,,,,
1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [105]:
#Table info
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16572 entries, 1 to 16600
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          16572 non-null  object
 1   Platform      16572 non-null  object
 2   Year          16301 non-null  float64
 3   Genre         16572 non-null  object
 4   Publisher     16514 non-null  object
 5   NA_Sales      16572 non-null  float64
 6   EU_Sales      16572 non-null  float64
 7   JP_Sales      16572 non-null  float64
 8   Other_Sales   16572 non-null  float64
 9   Global_Sales  16572 non-null  float64
dtypes: float64(6), object(4)
memory usage: 1.4+ MB
None

In [106]:
#Treating the dataframe

#Converting year to integer
df[['Year']] = df[['Year']].fillna(value=0)
df = df.astype({"Year": "int64"})

#Dropping null values from Publisher column
df = df.dropna(how="any", axis =0)

#Table info
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16514 entries, 1 to 16600
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          16514 non-null  object
 1   Platform      16514 non-null  object
 2   Year          16514 non-null  int64
 3   Genre         16514 non-null  object
 4   Publisher     16514 non-null  object
 5   NA_Sales      16514 non-null  float64
 6   EU_Sales      16514 non-null  float64
 7   JP_Sales      16514 non-null  float64
 8   Other_Sales   16514 non-null  float64
 9   Global_Sales  16514 non-null  float64
dtypes: float64(5), int64(1), object(4)
memory usage: 1.4+ MB
None

In [107]:
#GroupÃ­ng and defining variables

df_group = df.groupby(['Platform']).sum()
df_group = df_group.drop("Year", axis=1)

#Platform and value of max EU Sales
df_eu_sales = df_group.sort_values('EU_Sales', ascending=False)[:3]
eu_sales = df_eu_sales.iloc[0].values[1]
eu_plat  = df_eu_sales.iloc[0].name

#Platform and value of max Global Sales
df_global_sales = df_group.sort_values('Global_Sales', ascending=False)[:3]
global_sales = df_global_sales.iloc[0].values[4]
global_plat  = df_global_sales.iloc[0].name

In [108]:
#Send email using g-mail

gmail = "https://mail.google.com/mail/u/0/#inbox"

pg.hotkey("ctrl","t")
pc.copy(gmail)
pg.hotkey("ctrl","v")
pg.press("enter")

time.sleep(5)

pg.click(x=36, y=170, clicks = 1)

time.sleep(6)

#Recipient's email address
pg.write("xxxxx@gmail.com")
pg.press("tab")
pg.press("tab") 

#Email subject
pg.write ("Daily Sales")
pg.press("tab")

text=f"""
Good morning,

Considering EU, the platform with the highest sales amount is {eu_plat}, selling a total of {eu_sales:,.2f}.
Talking about Global sales, {global_plat} is the number one platform representing a total of {global_sales:,.2f}.

Regards

"""
pc.copy(text)
pg.hotkey("ctrl","v")
pg.hotkey("ctrl","enter")